# Generated by Django 3.2.4 on 2021-09-21 07:36

from django.db import migrations, models
import qrcode4e.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=qrcode4e.models.user_img_path)),
                ('decode_text', models.CharField(max_length=250, null=True)),
                ('sys_created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('sys_updated_date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
